[build]
  # Comando para buildar o projeto
  command = "npm run build"
  
  # Pasta onde ficam os arquivos estáticos após o build
  publish = "out"
  
  # Variáveis de ambiente
  [build.environment]
    NODE_VERSION = "20"
    NPM_VERSION = "10"

# Configurações de redirecionamento
[[redirects]]
  # Redirecionar todas as rotas para index.html (SPA)
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de headers para performance e segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers específicos para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para imagens
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para CSS e JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações para formulários Netlify
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configurações de deploy
[build.processing.images]
  compress = true
